---
title: "Section 1 Exercises"
author: "Enzo Gomes"
date: "2025-09-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Exercise 1 - reformatting spectra dataset

Load all the `.jdx` files of the `fusel alcohols` dataset into individual variables. Then:

1.  Find the units of the propanol IR spectra (e.g. is the y-axis in absorbance or transmittance?)

2.  Isolate the spectra of each compound into new variables.

3.  Compile all the spectra into a single variable. What type of data structure is best for this purpose?

4.  Save the compiled spectra to a `.rds` file.

## Exercise 2 - calculating rate constants

The combustion reaction of heptane is described by the equation:

$$
C_7H_{16} + O_2 \rightarrow products
$$

The rate constant of this reaction follows the Arrhenius Equation with a pre-exponential factor of `5.25*10^-7` cm3/mol\*s and an activation energy of `181` kJ/mol ([NIST](https://kinetics.nist.gov/kinetics/Detail?id=1975SHA/DEN872:4)). Calculate the rate constant at 410K, 420K and 430K.

## Exercise 3 - estimate IR spectra of mixtures

Load the `.rds` file you created in exercise 1 and isolate the spectra y-axis of the compounds propanol, pentanol and isobutyl alcohol into a single matrix (one compound per column).

1.   Generate a (uniform) random matrix containing 5 combinations of concentrations (with values between 0.2 and 1) for the 3 selected compounds.

2.  Use Beer-Lambert's Law to calculate the approximate spectra of each mixture in the previously generated matrix.

3.  Save the newly generated spectra as a `.csv` file.
